# Generated by Django 4.2 on 2024-12-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_trabajaconnosotros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculosclientes',
            name='unidad',
            field=models.CharField(max_length=50),
        ),
    ]
